name: Continuous Integration
on: 
  push:
    branches: [master]
env:
  SEMAPHORE_VERSION: 2.8.5
  GITHUB_REPO: fgierlinger/semaphore
jobs:
  bump_version:
    if: "!startsWith(github.event.head_commit.message, 'bump:') && github.event_name == 'push'"
    runs-on: ubuntu-latest
    name: "Bump version and create changelog with commitizen"
    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
  build:
    needs: bump_version
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - 
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - 
        name: Build fleet-server for arm64
        if: github.event_name == 'push'
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/arm64
          tags: ${{ env.GITHUB_REPO }}:${{ env.SEMAPHORE_VERSION }}
          file: Dockerfile
          build-args: SEMAPHORE_VERSION=${{ env.SEMAPHORE_VERSION }}
