name: Pull Request Check
on: 
  pull_request:
    branches: [master]
env:
  SEMAPHORE_VERSION: 2.7.16
  GITHUB_REPO: fgierlinger/semaphore
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - 
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Build fleet-server for arm64
        uses: docker/build-push-action@v2
        with:
          push: false
          platforms: linux/arm64
          tags: ${{ env.GITHUB_REPO }}:${{ env.SEMAPHORE_VERSION }}
          file: Dockerfile
          build-args: SEMAPHORE_VERSION=${{ env.SEMAPHORE_VERSION }}
